### ISSUE TITLE
Links to development and hosting are wrong

### ISSUE THREAD

**Issue by janhalen** [OS2compliance/OS2compliance-docs#3]
From the frontpage the links are linking to e.g. https://os2compliance.github.io/OS2compliance-docs/hosting.md instead of https://os2compliance.github.io/OS2compliance-docs/hosting resulting in a 404.

![image](https://github.com/OS2compliance/OS2compliance-docs/assets/50995332/3d6cb871-b0d5-47ca-ae70-3a1b73a03853)

**Comment by janhalen** [comment]
@kbp-di : I have added a plugin in the branch that should handle relative links... Do you want to test it?

**Comment by kbp-di** [comment]
Checked the commits - LGTM :)
